### ISSUE TITLE
Sources ?

### ISSUE THREAD

**Issue by TartanLeGrand** [containers/podman-machine-wsl-os#3]
Hello were is the sources of the distrib WSL ? 🤔 

Thanks!

**Comment by l0rd** [comment]
The source code that builds the WSL image for podman is in this [Cirrus CI manifest](https://github.com/containers/podman-machine-wsl-os/blob/main/.cirrus.yml). In particular:
- The image `docker.io/library/fedora` is pulled
- A container named `fedora-update` is started and the following commands are run:
  1. `dnf update -y`
  2. `dnf -y install podman podman-docker $PACKAGE_LIST`
  3. `dnf clean all`
  4. `rm -rf /var/cache/yum`
- The container content is exported: `podman export --output rootfs.tar fedora-update`
- File /etc/resolv.conf is removed from the roots.tar and replaced with an empty one
- roots.tar is compressed with zstd and [published on GH release page](https://github.com/containers/podman-machine-wsl-os/releases)

That's done for both `amd64` and `arm64` architectures. And v5.1 and v5.2 zstd files are identical.

**Comment by l0rd** [comment]
I have added a [README.md](https://github.com/containers/podman-machine-wsl-os/blob/main/README.md) file that should clarify how the build of the image works.
