### ISSUE TITLE
CIFS and NFS are not installed in WSL image

### ISSUE THREAD

**Issue by ThePMO** [containers/podman-machine-wsl-os#7]
Since I haven't found anything regarding this in any documentation I assume this is a bug:
The WSL image for the podman machine does not contain mount.cifs and mount.nfs, they need to be installed manually (cifs-utils and nfs-utils).

**Comment by Luap99** [comment]
I would not object to adding them, looking at our coreos images they seems to have  `cifs-utils` and `nfs-utils-coreos` (which seems to be smaller subset of nfs-utils) in there so I think it makes snese to add them to wsl images as well.
@l0rd @baude WDYT?

**Comment by l0rd** [comment]
I am ok. It's a 10% increase in size for the uncompressed tar. But if these packages are in fcos, it makes sense to add them in the current wsl image too. 

```
❯ ls -lh rootfs*.tar
-rw-r--r--. 1 mariolet mariolet 707M Sep 27 08:49 rootfs-current.tar
-rw-r--r--. 1 mariolet mariolet 784M Sep 27 08:46 rootfs-new.tar
```

If we are all okay with moving forward with this, here is a [PR](https://github.com/containers/podman-machine-wsl-os/pull/8) to add these 2 packages.
